// File generated by gg2c. https://github.com/pw32x/gg2c
#ifndef BACKGROUND_INCLUDE_H
#define BACKGROUND_INCLUDE_H

extern const unsigned short smallBackgroundMap[32 * 24];

extern const char backgroundTileset[32 * 2];

#endif

